// Minimal physical-design boundary for hardening the CPU core as an ASIC
// macro. Verification-only commit, RVFI, and debug signals remain internal.
module tdrv32_asic_wrapper #(
    parameter N = 32,
    parameter REG_DEPTH = 32,
    parameter logic [N-1:0] RESET_VECTOR = '0,
    parameter logic [N-1:0] MVENDOR_ID = '0,
    parameter logic [N-1:0] MARCH_ID = '0,
    parameter logic [N-1:0] MIMP_ID = '0,
    parameter logic [N-1:0] HART_ID = '0,
    parameter logic [N-1:0] CONFIG_PTR = '0
)(
    input  logic i_clk,
    input  logic i_arst_n,

    input  logic i_irq_software,
    input  logic i_irq_timer,
    input  logic i_irq_external,
    input  logic [63:0] i_time,

    output logic o_core_sleep,
    output logic o_fence_i,

    output logic         o_imem_valid,
    output logic [N-1:0] o_imem_addr,
    input  logic [N-1:0] i_imem_rdata,
    input  logic         i_imem_ready,
    input  logic         i_imem_error,

    output logic         o_dmem_valid,
    output logic         o_dmem_read,
    output logic         o_dmem_write,
    output logic [N-1:0] o_dmem_addr,
    output logic [N-1:0] o_dmem_wdata,
    output logic [3:0]   o_dmem_wstrb,
    output logic [1:0]   o_dmem_size,
    input  logic [N-1:0] i_dmem_rdata,
    input  logic         i_dmem_ready,
    input  logic         i_dmem_error
);

    tdrv32_core #(
        .N(N),
        .REG_DEPTH(REG_DEPTH),
        .RESET_VECTOR(RESET_VECTOR),
        .MVENDOR_ID(MVENDOR_ID),
        .MARCH_ID(MARCH_ID),
        .MIMP_ID(MIMP_ID),
        .HART_ID(HART_ID),
        .CONFIG_PTR(CONFIG_PTR),
        .ENABLE_DEBUG_SHADOWS(1'b0)
    ) u_core (
        .i_clk(i_clk),
        .i_arst_n(i_arst_n),
        .i_irq_software(i_irq_software),
        .i_irq_timer(i_irq_timer),
        .i_irq_external(i_irq_external),
        .i_time(i_time),
        .o_core_sleep(o_core_sleep),
        .o_fence_i(o_fence_i),
        .o_imem_valid(o_imem_valid),
        .o_imem_addr(o_imem_addr),
        .i_imem_rdata(i_imem_rdata),
        .i_imem_ready(i_imem_ready),
        .i_imem_error(i_imem_error),
        .o_dmem_valid(o_dmem_valid),
        .o_dmem_read(o_dmem_read),
        .o_dmem_write(o_dmem_write),
        .o_dmem_addr(o_dmem_addr),
        .o_dmem_wdata(o_dmem_wdata),
        .o_dmem_wstrb(o_dmem_wstrb),
        .o_dmem_size(o_dmem_size),
        .i_dmem_rdata(i_dmem_rdata),
        .i_dmem_ready(i_dmem_ready),
        .i_dmem_error(i_dmem_error),
        .o_commit_valid(),
        .o_commit_pc(),
        .o_commit_instruction(),
        .o_commit_rd_write(),
        .o_commit_rd_addr(),
        .o_commit_rd_data(),
        .o_commit_mem_write(),
        .o_commit_mem_addr(),
        .o_commit_mem_wdata(),
        .o_commit_mem_wstrb(),
        .o_debug_pc(),
        .o_debug_instruction(),
        .o_debug_rs1_data(),
        .o_debug_rs2_data(),
        .o_debug_alu_operand_b(),
        .o_debug_branch_target(),
        .o_debug_alu_result(),
        .o_debug_wb_data(),
        .o_debug_rd_addr(),
        .o_debug_rd_write(),
        .o_debug_mem_write(),
        .o_debug_mem_read(),
        .o_debug_branch_taken(),
        .o_debug_mem_addr(),
        .o_debug_mem_wdata(),
        .o_debug_mem_rdata(),
        .o_debug_jal(),
        .o_debug_jalr(),
        .o_debug_stall(),
        .o_debug_flush(),
        .o_debug_immediate(),
        .o_debug_alu_uses_immediate()
    );

endmodule
